var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xx                                                                        xx  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                xxxxx                                     x  ",
   "  x                                x                                  o o o  x  ",
   "  x                                xoooo                             o o o o x  ",
   "  x                p               xxxxx         x                 xxxxxxxxxxx  ",
   "  x                x                            x!x       xxx                x  ",
   "  x         o     x!x                      x   xxxxx       xxx               x  ",
   "  x         x      x      o               x!x               xxx              x  ",
   "  x        x!x o   o   o x!x             x!!!x               xxx             x  ",
   "  x         x             x             xxxxxxx               xxxxxx         x  ",
   "  x                                                                       w  x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxxxxxxxxxx   xxxxxxxxxx   xxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxx  ",
   "                 x   x        x   x           x            x                    ",
   "                 x!!!x        x!!!x           x!!!!!!!!!!!!x                    ",
   "                 x!!!x        x!!!x           x!!!!!!!!!!!!x                    ",
   "                 xxxxx        xxxxx           xxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                               x                                                             xxx  ",
   "                                               x                                                             x+x  ",
   "                                               x                                                             x+x  ",
   "                                               x                                                             x+x  ",
   "                                               x  w                                                          x+x  ",
   "   x!!!!!!!!!!!!!!!!!!!!!!x                    x                                                    o   o    x+x  ",
   "   xxx!xxxxxxxx!xxxxxxxxx!x                    x   x!!!x          x!!!x          x!!!x            o   o   o  x+x  ",
   "      v        v         v                     x    x!x            x!x            x!x               o   o   xx+x  ",
   "                                               x     v              v              v          xxxxxxxxxxxxxxxxxx  ",
   "                                               x                                            xx----------------xx  ",
   "                                               x                                          xxxxxxxxxxxxxxxxxxxxx   ",
   "                                               x                                                                  ",
   "                              x                x                                                                  ",
   "                                               x     x                           xxx         xxx                  ",
   "                                               x     x=      -      =      -   =xxxx         x                    ",
   "                                               x     x                             x         x                    ",
   "                    x                          x-    x                             x        xx                    ",
   "                                               xx    x                            -x         x                    ",
   "                                               x     x      o  o     xxxxx         x         x                    ",
   "                                               x     x               x   x         x         x                    ",
   "          x                                    x    -x     xxxxxx    x   x+ +xxxxxxxxx       x                    ",
   "                                               x    xx               x   x- -x               x                    ",
   "                                               x     x               x   xxxxx               x                    ",
   " @                                             x     x               x ooooooo   xxx         x                    ",
   "xxx                               oooooooooooo x-    x               x ooooooo   x x         x                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ooo  ooo ooo xx    x!!!!!!!!!!!!!!!x     +     x x         x                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!o  o  o  o   x     x!!!!!!!xxxxxxxxxx!!!!!!!!!xx xx  o o  xx                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   vo  o  o  ooo     xx!!!!!!xx         xxxxxxxxxxx  xx!!!!!!xx                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    o  o  o  o   p   xx!!!!!!xx                       xxxxxxxx                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    ooo  ooo ooo xxxxx!!!!!!xx                                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                      xx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                      x   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "  x                                   x   x           x                     xxx                               ",
   "  x                                   x   xx          x                                                       ",
   "  x                                   x   x= = = =    x            xxx                                        ",
   "  x                                   x   x           x           x!!!x                                       ",
   "  x                                   x   x    = = = =x     o      xxx       xxx                              ",
   "  x                                   x   xx          x                     x!!!x                             ",
   "  x                                   x   x           x     x                xxv        xxx                   ",
   "  x                                   x   x           x              x                 x!!!x                  ",
   "  x                          xxxxxxxxxxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "  x                          x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "  x                          x     |||     x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "  x                          xx           xx                                         xxx                      ",
   "  x              x            x    + +    x                                         x!!!x                xxx  ",
   "  x                           x           x                                          xxx                 x x  ",
   "  x       x                   x           xxxxxxx                        xxxxx                             x  ",
   "  x                         xxx           x                              x   x                             x  ",
   "  xx                        x             x                              x x x                             x  ",
   "  x                         x w           x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                         x      + +                                   x         xxx                     x  ",
   "  x                         xxx                                         xxx       x!!!x          x         x  ",
   "  xx                      -   x    |||                                  x x        xxx          xxx        x  ",
   "  xx                     ---  xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  xx     @                -   x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "  xx                                                                        xx  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x                                                                          x  ",
    "  x              o o ooo o o   o   o ooo o   o o                             x  ",
    "  x              o o o o o o   o   o  o  oo  o o                             x  ",
    "  x               o  o o o o   o   o  o  o o o o                             x  ",
    "  x               o  o o o o   o o o  o  o  oo                               x  ",
    "  x  @            o  ooo ooo   oo oo ooo o   o o                             x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                ",
    "                                                                                "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
